spring.application.name=edzybackend

# Server
server.port=8081

# MongoDB : always use URI to avoid falling back to 'test' db
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/edzy}

# Logging
logging.level.org.springframework=INFO
logging.level.org.mongodb.driver=DEBUG

# Secret Key
#jwt.secret=${JWT_SECRET}
jwt.secret=edzy_super_secret_key_must_be_32_chars!!

spring.main.allow-bean-definition-overriding=true